% A First Look at the 2012 Election
% Eric Hare & Andee Kaplan
% Dec. 6th 2012

```{r setup, echo=FALSE, message=FALSE, warning=FALSE}
# Source in our code
source("../../Code/MergedCleanup.R")
```

# Motivation

# Data Sources

# Cleanup

# Types of Spending by Week

```{r SpendingByWeek, echo=FALSE, fig.cap='Spending by Super PACs in support or opposition of candidates', message=FALSE, warning=FALSE}
library(ggplot2)
ggplot(num.weeks, aes(date, WeeklySum, colour = beneful_can)) + geom_point() + geom_line() + facet_grid(facets=bucket2~sup_opp) + 
    scale_colour_manual(name = "Candidate who benefits", values = c("#3D64FF", "#CC0033"), labels=c("Obama","Romney" )) + 
    xlab("Weeks") + 
    ylab("Amount Spent (Log 10)") + 
    annotate(geom = "rect", xmin = as.Date("2012-8-11", format="%Y-%m-%d"), xmax = as.Date("2012-8-12", format="%Y-%m-%d"), ymin = 1, ymax = 1e+08, alpha = .2, fill = "#CC0033") + 
    annotate(geom = "rect", xmin = as.Date("2012-8-28", format="%Y-%m-%d"), xmax = as.Date("2012-8-30", format="%Y-%m-%d"), ymin = 1, ymax = 1e+08, alpha = .2, fill = "#CC0033") + 
    annotate(geom = "rect", xmin = as.Date("2012-9-4", format="%Y-%m-%d"), xmax = as.Date("2012-9-6", format="%Y-%m-%d"), ymin = 1, ymax = 1e+08, alpha = .2, fill = "#3D64FF") + 
    annotate(geom = "rect", xmin = as.Date("2012-9-17", format="%Y-%m-%d"), xmax = as.Date("2012-9-18", format="%Y-%m-%d"), ymin = 1, ymax = 1e+08, alpha = .2, fill = "grey50") + 
    annotate(geom = "rect", xmin = as.Date("2012-10-3", format="%Y-%m-%d"), xmax = as.Date("2012-10-4", format="%Y-%m-%d"), ymin = 1, ymax = 1e+08, alpha = .2, fill = "grey50") + 
    scale_y_log10() + 
    theme(legend.position="bottom")
```